// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*! 
 * @file Plot.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _M5STACK_MSGS_PLOT_HPP_
#define _M5STACK_MSGS_PLOT_HPP_

#include "../topic.hpp"

namespace m5stack_msgs {

class Plot : public ros2::Topic<Plot>
{
public:
    char name[32];
    int16_t data[320];

    Plot():
        Topic("m5stack_msgs::msg::dds_::Plot_", "Plot", M5STACK_MSGS_PLOT_ID)
    {
    }  

    bool serialize(void* msg_buf, const Plot* topic)
    {
        ucdrBuffer* writer = (ucdrBuffer*)msg_buf;
        (void) ucdr_serialize_array_char(writer, topic->name, sizeof(topic->name) / sizeof(char));
        (void) ucdr_serialize_array_int16_t(writer, topic->data, sizeof(topic->data) / sizeof(int16_t));

        return !writer->error;
    }

    bool deserialize(void* msg_buf, Plot* topic)
    {
        ucdrBuffer* reader = (ucdrBuffer*)msg_buf;
        (void) ucdr_deserialize_array_char(reader, topic->name, sizeof(topic->name) / sizeof(char));
        (void) ucdr_deserialize_array_int16_t(reader, topic->data, sizeof(topic->data) / sizeof(int16_t));

        return !reader->error;
    }

    uint32_t size_of_topic(const Plot* topic, uint32_t size)
    {
        uint32_t previousSize = size;
        size += ucdr_alignment(size, 1) + sizeof(topic->name);
        size += ucdr_alignment(size, 2) + sizeof(topic->data);

        return size - previousSize;
    }
};
}
#endif // _M5STACK_MSGS_PLOT_HPP_
